-- Consumable SHOP churn through the real engine adapter -> reader -> policy
-- path (docs/CLAUDE_BATCH3_REVIEW.md M2, L2). Unlike the hand-built fixtures,
-- every frame here is observed, exported and regenerated by the real adapter,
-- reader and actions modules, so the credentials the policy sees are exactly
-- the ones the executor would accept.
--
-- The four states:
--   * full slots with no certified BUY_ITEM: one justified sale of the weakest
--     held Tarot for a visible, affordable, strictly better offer;
--   * the freed slot makes the adapter actually certify the purchase: the policy
--     buys it, and with better Tarots held and an empty shop it retains them;
--   * the safety floor (harmful / unusable consumables) is unchanged;
--   * a Negative consumable needs no slot, so it is bought without any sale.
return function(ctx)
	local test = ctx.test
	local Support = ctx.support
	local env = Support.env(ctx.repo_root)
	local Engine = dofile(ctx.repo_root .. "/tests/engine/support.lua")
	local bundle = Engine.bundle(ctx.repo_root)
	local STATES = Engine.STATES
	local STRONG = { "competitive", "major_league", "expert" }

	local function tarot(center, opts)
		opts = opts or {}
		return Engine.card({
			set = "Tarot", consumeable = true, center = center, center_set = "Tarot",
			-- A highlighted-target Tarot: never offered as a direct, target-free
			-- USE_CONSUMABLE (it needs hand cards).
			consumeable_data = { max_highlighted = 2, min_highlighted = 1 },
			area_type = "joker", rank = "Ace", suit = "Spades",
			cost = opts.cost, edition = opts.edition, card_limit = opts.card_limit,
		})
	end

	local function shop(shop_items, held, money, slots)
		return Engine.engine({
			state = STATES.SHOP,
			consumeables = held,
			consumable_slots = slots or 2,
			shop_jokers = shop_items,
			dollars = money or 30,
		})
	end

	-- Current Steamodded recomputes a CardArea limit from the owned row:
	--   total = base + mod + sum(owned ability.card_limit)
	--   card_limit = total - sum(owned ability.extra_slots_used)
	-- (src/utils.lua:3919, lovely/card_limit.toml:120-166, read-only). Re-settle
	-- after every sale/buy so the observed `consumable_slots` follows the live
	-- handle_card_limit semantics: an owned Negative owns card_limit = 1.
	local function settle(engine)
		local limits = engine.consumeables.config.card_limits
		local extra, used = 0, 0
		for _, c in ipairs(engine.consumeables.cards) do
			extra = extra + (c.ability.card_limit or 0)
			used = used + (c.ability.extra_slots_used or 0)
		end
		limits.extra_slots = extra
		limits.extra_slots_used = used
		limits.total_slots = (limits.base or 0) + (limits.mod or 0) + extra
	end

	local function decide_export(difficulty, export)
		local result = env.policy_env.run(Support.source(env, difficulty), export)
		ctx.is_true(result.ok == true, difficulty .. ":" .. tostring(result.code))
		return result.action
	end

	local function observed(engine)
		local pipeline = Engine.pipeline(bundle, engine, {})
		local result, code = pipeline.adapter.step()
		assert(result ~= nil, "adapter: " .. tostring(code))
		local handle, rcode = bundle.reader.capture(result.runtime, result.ui_view)
		assert(handle ~= nil, "capture: " .. tostring(rcode))
		return bundle.obs.export(handle), bundle.actions.generate(handle)
	end

	local function certified(actions)
		local seen = {}
		for i = 1, #actions do
			seen[actions[i].type] = true
		end
		return seen
	end

	local function decide(difficulty, engine)
		local export = observed(engine)
		local result = env.policy_env.run(Support.source(env, difficulty), export)
		ctx.is_true(result.ok == true, difficulty .. ":" .. tostring(result.code))
		return result.action
	end

	test("full_slots_without_a_certified_buy_do_not_churn", function()
		for _, d in ipairs(STRONG) do
			local engine = shop({ tarot("c_strength", { cost = 3 }) }, { tarot("c_death"), tarot("c_sun") })
			local _, actions = observed(engine)
			ctx.truthy(certified(actions).BUY_ITEM ~= true, d .. " no BUY_ITEM while the slots are full")
			ctx.truthy(certified(actions).SELL_CONSUMABLE == true, d .. " SELL_CONSUMABLE offered")
			local action = decide(d, engine)
			-- The Sun (worth 1) is the weakest held Tarot and the only one sold.
			ctx.eq(action.type, "SELL_CONSUMABLE", d .. " sells")
			ctx.eq(action.consumable_ref, "consumable:2", d .. " weakest held")
		end
	end)

	test("a_sale_frees_the_slot_for_the_newly_certified_buy_then_retains", function()
		for _, d in ipairs(STRONG) do
			-- The slot was just freed, so the adapter now certifies the purchase.
			local engine = shop({ tarot("c_strength", { cost = 3 }) }, { tarot("c_death") })
			local _, actions = observed(engine)
			ctx.truthy(certified(actions).BUY_ITEM == true, d .. " BUY_ITEM with a free slot")
			local action = decide(d, engine)
			ctx.eq(action.type, "BUY_ITEM", d .. " buys")
			ctx.eq(action.item_ref, "shop:1", d .. " the offered item")

			-- Full again with the better Tarot and an empty shop: no further sale.
			local retained = shop({}, { tarot("c_death"), tarot("c_strength") })
			ctx.eq(decide(d, retained).type, "LEAVE_SHOP", d .. " retains")
		end
	end)

	test("safety_floor_sales_survive_the_real_adapter", function()
		for _, d in ipairs(Support.DIFFICULTIES) do
			local harmful = shop({}, { tarot("c_ectoplasm") }, 30, 1)
			ctx.eq(decide(d, harmful).type, "SELL_CONSUMABLE", d .. " harmful Spectral")
			local unusable = shop({}, { tarot("c_magician") }, 30, 1)
			ctx.eq(decide(d, unusable).type, "SELL_CONSUMABLE", d .. " unusable targeted Tarot")
		end
	end)

	test("a_negative_consumable_is_bought_without_freeing_a_slot", function()
		for _, d in ipairs(STRONG) do
			local engine = shop(
				{ tarot("c_strength", { cost = 3, edition = "negative", card_limit = 1 }) },
				{ tarot("c_death"), tarot("c_sun") })
			local _, actions = observed(engine)
			ctx.truthy(certified(actions).BUY_ITEM == true, d .. " negative BUY_ITEM over full slots")
			local action = decide(d, engine)
			ctx.eq(action.type, "BUY_ITEM", d .. " buys the negative")
			ctx.eq(action.item_ref, "shop:1", d .. " item")
		end
	end)

	test("shop_churn_decisions_are_deterministic", function()
		for _, d in ipairs(STRONG) do
			local engine = shop({ tarot("c_strength", { cost = 3 }) }, { tarot("c_death"), tarot("c_sun") })
			local first = decide(d, engine)
			local second = decide(d, engine)
			ctx.eq(second.id, first.id, d .. " stable")
			ctx.vector("shop_churn_" .. d, first.type .. ":" .. tostring(first.consumable_ref or first.item_ref))
		end
	end)

	-- L-b: after a justified sale, two equal-priced consumables score the same,
	-- so the tie must be broken by SLOT_WORTH, not by the shop reference order.
	test("a_justified_sale_buys_the_higher_worth_offer", function()
		for _, d in ipairs(STRONG) do
			-- Star (worth 1) at shop:1, Saturn (worth 9) at shop:2, one slot.
			local full = shop({ tarot("c_star", { cost = 3 }), tarot("c_saturn", { cost = 3 }) },
				{ tarot("c_death") }, 30, 1)
			ctx.eq(decide(d, full).type, "SELL_CONSUMABLE", d .. " sells for the upgrade")
			local freed = shop({ tarot("c_star", { cost = 3 }), tarot("c_saturn", { cost = 3 }) }, {}, 30, 1)
			local buy = decide(d, freed)
			ctx.eq(buy.type, "BUY_ITEM", d .. " buys")
			ctx.eq(buy.item_ref, "shop:2", d .. " Saturn, the higher worth")
			local retained = shop({}, { tarot("c_saturn") }, 30, 1)
			ctx.eq(decide(d, retained).type, "LEAVE_SHOP", d .. " retains")
		end
	end)

	test("the_higher_worth_offer_wins_regardless_of_shop_order", function()
		for _, d in ipairs(STRONG) do
			-- Saturn at shop:1, Star at shop:2: still Saturn.
			local freed = shop({ tarot("c_saturn", { cost = 3 }), tarot("c_star", { cost = 3 }) }, {}, 30, 1)
			ctx.eq(decide(d, freed).item_ref, "shop:1", d .. " Saturn first")
		end
	end)

	test("equal_worth_offers_keep_the_deterministic_id_order", function()
		for _, d in ipairs(STRONG) do
			-- Star and Moon are both worth 1, so the established id order decides.
			local freed = shop({ tarot("c_star", { cost = 3 }), tarot("c_moon", { cost = 3 }) }, {}, 30, 1)
			local first = decide(d, freed)
			ctx.eq(first.item_ref, "shop:1", d .. " id order")
			ctx.eq(decide(d, freed).id, first.id, d .. " stable")
		end
	end)

	test("a_negative_high_worth_offer_is_bought_over_full_slots", function()
		for _, d in ipairs(STRONG) do
			local engine = shop(
				{ tarot("c_saturn", { cost = 3, edition = "negative", card_limit = 1 }) },
				{ tarot("c_death"), tarot("c_sun") })
			local action = decide(d, engine)
			ctx.eq(action.type, "BUY_ITEM", d .. " buys the negative")
			ctx.eq(action.item_ref, "shop:1", d .. " item")
		end
	end)

	-- The equal-scored tie-break must not depend on certificate order: with
	-- LEAVE_SHOP listed first, the higher-worth consumable still wins.
	test("the_buy_tiebreak_ignores_certificate_order", function()
		local function frame(order)
			local self = {
				money = 30, credit_limit = 0, hands = 4, discards = 3, current_score = "0",
				blind_requirement = "100", hand_visible = false, jokers = {}, consumables = {},
				vouchers = {}, tags = {}, deck = { total = 52 },
			}
			local items = {}
			for i = 1, #order do
				items[i] = { kind = "consumable", center = order[i], cost = 3, face_down = false }
			end
			return {
				schema_version = 1, phase = "SHOP", match = Support.match(), self = self,
				shop = { reroll_cost = 5, items = items, vouchers = {}, boosters = {} },
				context = { blocked = false, timer_expired = false },
				certificates = { version = 1, items = {
					{ type = "LEAVE_SHOP", certified = true },
					{ type = "BUY_ITEM", certified = true, item_ref = "shop:1", capacity_ok = true },
					{ type = "BUY_ITEM", certified = true, item_ref = "shop:2", capacity_ok = true },
				} },
			}
		end
		for _, d in ipairs(STRONG) do
			local result = Support.run(env, d, frame({ "c_star", "c_saturn" }))
			ctx.is_true(result.ok == true, d .. ":" .. tostring(result.code))
			ctx.eq(result.action.type, "BUY_ITEM", d .. " buys")
			ctx.eq(result.action.item_ref, "shop:2", d .. " Saturn despite LEAVE_SHOP first")
		end
	end)

	-- Interest-breakpoint churn (final review): Star cheaper than Saturn means a
	-- hidden sale-proceeds interest step would flip the next buy to Star, so the
	-- sale is refused; a Saturn that is not more expensive stays justified.
	test("interest_breakpoint_sale_rationale_uses_the_actual_best_purchase", function()
		for _, d in ipairs(STRONG) do
			local hold = shop({ tarot("c_star", { cost = 3 }), tarot("c_saturn", { cost = 4 }) },
				{ tarot("c_death"), tarot("c_sun") }, 22, 2)
			ctx.neq(decide(d, hold).type, "SELL_CONSUMABLE", d .. " no churn")
			local sell = shop({ tarot("c_star", { cost = 4 }), tarot("c_saturn", { cost = 3 }) },
				{ tarot("c_death"), tarot("c_sun") }, 22, 2)
			local action = decide(d, sell)
			ctx.eq(action.type, "SELL_CONSUMABLE", d .. " sells")
			ctx.eq(action.consumable_ref, "consumable:2", d .. " the weakest held")
		end
	end)

	test("interest_breakpoint_cycle_never_sells_buys_sells", function()
		for _, d in ipairs(STRONG) do
			local engine = shop({ tarot("c_star", { cost = 3 }), tarot("c_saturn", { cost = 4 }) },
				{ tarot("c_death"), tarot("c_sun") }, 22, 2)
			engine.consumeables.config.type = "joker"
			local sales, buys = 0, 0
			for _ = 1, 6 do
				for _, c in ipairs(engine.consumeables.cards) do c.area = engine.consumeables end
				for _, c in ipairs(engine.G.shop_jokers.cards) do c.area = engine.G.shop_jokers end
				local action = decide(d, engine)
				if action.type == "SELL_CONSUMABLE" then
					local idx = tonumber(action.consumable_ref:match("^consumable:(%d+)$"))
					local card = table.remove(engine.consumeables.cards, idx)
					engine.G.GAME.dollars = engine.G.GAME.dollars + card.sell_cost
					sales = sales + 1
				elseif action.type == "BUY_ITEM" then
					local idx = tonumber(action.item_ref:match("^shop:(%d+)$"))
					local card = table.remove(engine.G.shop_jokers.cards, idx)
					engine.consumeables.cards[#engine.consumeables.cards + 1] = card
					engine.G.GAME.dollars = engine.G.GAME.dollars - card.cost
					buys = buys + 1
				else
					break
				end
			end
			ctx.is_true(sales <= 1 and buys <= 1, d .. " no churn sales=" .. sales .. " buys=" .. buys)
			ctx.eq(engine.G.GAME.dollars, 22, d .. " money preserved")
		end
	end)

	-- Astra negative-slot finding: a full Death + Strength + Negative Sun row
	-- (base 2 + the Negative's card_limit 1 = 3) offers Star and Saturn. Selling
	-- the Negative frees no slot (its own removal lowers the limit), so the
	-- policy must keep it, sell only the regular Strength, then buy Saturn.
	-- Both offer orders and a LEAVE_SHOP-first certificate order are exercised,
	-- and no repeated or unhelpful sale is allowed afterwards.
	test("an_owned_negative_is_kept_through_the_real_adapter_multi_step", function()
		local orders = {
			{ "c_star", "c_saturn" },
			{ "c_saturn", "c_star" },
		}
		for _, d in ipairs(STRONG) do
			for o = 1, #orders do
				for _, leaves_first in ipairs({ false, true }) do
					local engine = shop(
						{ tarot(orders[o][1], { cost = 3 }), tarot(orders[o][2], { cost = 3 }) },
						{ tarot("c_death"), tarot("c_strength"), tarot("c_sun", { edition = "negative", card_limit = 1 }) },
						36, 2)
					engine.consumeables.config.type = "joker"
					settle(engine)
					ctx.eq(observed(engine).match.consumable_slots, 3, d .. " settled slots = base 2 + 1")

					local sales, buys = 0, 0
					for _ = 1, 5 do
						for _, c in ipairs(engine.consumeables.cards) do c.area = engine.consumeables end
						for _, c in ipairs(engine.G.shop_jokers.cards) do c.area = engine.G.shop_jokers end
						local export = observed(engine)
						if leaves_first then
							local ordered = {}
							for _, x in ipairs(export.certificates.items) do
								if x.type == "LEAVE_SHOP" then ordered[#ordered + 1] = x end
							end
							for _, x in ipairs(export.certificates.items) do
								if x.type ~= "LEAVE_SHOP" then ordered[#ordered + 1] = x end
							end
							export.certificates.items = ordered
						end
						local action = decide_export(d, export)
						if action.type == "SELL_CONSUMABLE" then
							local idx = tonumber(action.consumable_ref:match("^consumable:(%d+)$"))
							local card = table.remove(engine.consumeables.cards, idx)
							ctx.neq(card.config.center.key, "c_sun", d .. " never sells the Negative")
							engine.G.GAME.dollars = engine.G.GAME.dollars + card.sell_cost
							sales = sales + 1
						elseif action.type == "BUY_ITEM" then
							local idx = tonumber(action.item_ref:match("^shop:(%d+)$"))
							local card = table.remove(engine.G.shop_jokers.cards, idx)
							engine.consumeables.cards[#engine.consumeables.cards + 1] = card
							engine.G.GAME.dollars = engine.G.GAME.dollars - card.cost
							buys = buys + 1
						else
							break
						end
						settle(engine)
					end
					ctx.eq(sales, 1, d .. " exactly one sale")
					ctx.eq(buys, 1, d .. " exactly one buy")
					ctx.eq(engine.G.GAME.dollars, 34, d .. " sold one (+1), bought Saturn (-3)")
					local centers = {}
					for _, c in ipairs(engine.consumeables.cards) do centers[c.config.center.key] = true end
					ctx.truthy(centers.c_sun == true, d .. " Negative Sun kept")
					ctx.truthy(centers.c_saturn == true, d .. " Saturn bought")
					ctx.truthy(centers.c_strength ~= true, d .. " regular Strength sold")
				end
			end
		end
	end)

	-- The settled capacity itself: removing the Negative lowers the observed
	-- consumable_slots by its owned card_limit (3 -> 2); removing a regular card
	-- leaves it unchanged.
	test("a_negative_consumable_recomputes_the_settled_capacity", function()
		local engine = shop({}, {
			tarot("c_death"), tarot("c_strength"),
			tarot("c_sun", { edition = "negative", card_limit = 1 }),
		}, 36, 2)
		settle(engine)
		ctx.eq(observed(engine).match.consumable_slots, 3, "base 2 + negative 1")

		table.remove(engine.consumeables.cards, 1)
		settle(engine)
		ctx.eq(observed(engine).match.consumable_slots, 3, "a regular removal keeps the Negative's slot")

		table.remove(engine.consumeables.cards, 2)
		settle(engine)
		ctx.eq(observed(engine).match.consumable_slots, 2, "the Negative removal lowers the limit")
	end)
end
