-- Consumable SHOP churn through the real engine adapter -> reader -> policy
-- path (docs/CLAUDE_BATCH3_REVIEW.md M2, L2). Unlike the hand-built fixtures,
-- every frame here is observed, exported and regenerated by the real adapter,
-- reader and actions modules, so the credentials the policy sees are exactly
-- the ones the executor would accept.
--
-- The four states:
--   * full slots with no certified BUY_ITEM: one justified sale of the weakest
--     held Tarot for a visible, affordable, strictly better offer;
--   * the freed slot makes the adapter actually certify the purchase: the policy
--     buys it, and with better Tarots held and an empty shop it retains them;
--   * the safety floor (harmful / unusable consumables) is unchanged;
--   * a Negative consumable needs no slot, so it is bought without any sale.
return function(ctx)
	local test = ctx.test
	local Support = ctx.support
	local env = Support.env(ctx.repo_root)
	local Engine = dofile(ctx.repo_root .. "/tests/engine/support.lua")
	local bundle = Engine.bundle(ctx.repo_root)
	local STATES = Engine.STATES
	local STRONG = { "competitive", "major_league", "expert" }

	local function tarot(center, opts)
		opts = opts or {}
		return Engine.card({
			set = "Tarot", consumeable = true, center = center, center_set = "Tarot",
			-- A highlighted-target Tarot: never offered as a direct, target-free
			-- USE_CONSUMABLE (it needs hand cards).
			consumeable_data = { max_highlighted = 2, min_highlighted = 1 },
			area_type = "joker", rank = "Ace", suit = "Spades",
			cost = opts.cost, edition = opts.edition, card_limit = opts.card_limit,
		})
	end

	local function shop(shop_items, held, money, slots)
		return Engine.engine({
			state = STATES.SHOP,
			consumeables = held,
			consumable_slots = slots or 2,
			shop_jokers = shop_items,
			dollars = money or 30,
		})
	end

	local function observed(engine)
		local pipeline = Engine.pipeline(bundle, engine, {})
		local result, code = pipeline.adapter.step()
		assert(result ~= nil, "adapter: " .. tostring(code))
		local handle, rcode = bundle.reader.capture(result.runtime, result.ui_view)
		assert(handle ~= nil, "capture: " .. tostring(rcode))
		return bundle.obs.export(handle), bundle.actions.generate(handle)
	end

	local function certified(actions)
		local seen = {}
		for i = 1, #actions do
			seen[actions[i].type] = true
		end
		return seen
	end

	local function decide(difficulty, engine)
		local export = observed(engine)
		local result = env.policy_env.run(Support.source(env, difficulty), export)
		ctx.is_true(result.ok == true, difficulty .. ":" .. tostring(result.code))
		return result.action
	end

	test("full_slots_without_a_certified_buy_do_not_churn", function()
		for _, d in ipairs(STRONG) do
			local engine = shop({ tarot("c_strength", { cost = 3 }) }, { tarot("c_death"), tarot("c_sun") })
			local _, actions = observed(engine)
			ctx.truthy(certified(actions).BUY_ITEM ~= true, d .. " no BUY_ITEM while the slots are full")
			ctx.truthy(certified(actions).SELL_CONSUMABLE == true, d .. " SELL_CONSUMABLE offered")
			local action = decide(d, engine)
			-- The Sun (worth 1) is the weakest held Tarot and the only one sold.
			ctx.eq(action.type, "SELL_CONSUMABLE", d .. " sells")
			ctx.eq(action.consumable_ref, "consumable:2", d .. " weakest held")
		end
	end)

	test("a_sale_frees_the_slot_for_the_newly_certified_buy_then_retains", function()
		for _, d in ipairs(STRONG) do
			-- The slot was just freed, so the adapter now certifies the purchase.
			local engine = shop({ tarot("c_strength", { cost = 3 }) }, { tarot("c_death") })
			local _, actions = observed(engine)
			ctx.truthy(certified(actions).BUY_ITEM == true, d .. " BUY_ITEM with a free slot")
			local action = decide(d, engine)
			ctx.eq(action.type, "BUY_ITEM", d .. " buys")
			ctx.eq(action.item_ref, "shop:1", d .. " the offered item")

			-- Full again with the better Tarot and an empty shop: no further sale.
			local retained = shop({}, { tarot("c_death"), tarot("c_strength") })
			ctx.eq(decide(d, retained).type, "LEAVE_SHOP", d .. " retains")
		end
	end)

	test("safety_floor_sales_survive_the_real_adapter", function()
		for _, d in ipairs(Support.DIFFICULTIES) do
			local harmful = shop({}, { tarot("c_ectoplasm") }, 30, 1)
			ctx.eq(decide(d, harmful).type, "SELL_CONSUMABLE", d .. " harmful Spectral")
			local unusable = shop({}, { tarot("c_magician") }, 30, 1)
			ctx.eq(decide(d, unusable).type, "SELL_CONSUMABLE", d .. " unusable targeted Tarot")
		end
	end)

	test("a_negative_consumable_is_bought_without_freeing_a_slot", function()
		for _, d in ipairs(STRONG) do
			local engine = shop(
				{ tarot("c_strength", { cost = 3, edition = "negative", card_limit = 1 }) },
				{ tarot("c_death"), tarot("c_sun") })
			local _, actions = observed(engine)
			ctx.truthy(certified(actions).BUY_ITEM == true, d .. " negative BUY_ITEM over full slots")
			local action = decide(d, engine)
			ctx.eq(action.type, "BUY_ITEM", d .. " buys the negative")
			ctx.eq(action.item_ref, "shop:1", d .. " item")
		end
	end)

	test("shop_churn_decisions_are_deterministic", function()
		for _, d in ipairs(STRONG) do
			local engine = shop({ tarot("c_strength", { cost = 3 }) }, { tarot("c_death"), tarot("c_sun") })
			local first = decide(d, engine)
			local second = decide(d, engine)
			ctx.eq(second.id, first.id, d .. " stable")
			ctx.vector("shop_churn_" .. d, first.type .. ":" .. tostring(first.consumable_ref or first.item_ref))
		end
	end)
end
